name: Update News

on:
  schedule:
    - cron: '0 */4 * * *'  # runs every 4 hours, change as you want
  workflow_dispatch:        # manual trigger available


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run your script
        run: python main.py
